[app]
env = "DEVELOPMENT"
port = 8080
client_domain = "http://localhost:3000"
cookie_domain = "localhost"
cookie_secure = true

[database]
url = "postgres://postgres:1234@localhost:5432/postgre"
pool_max_conns = 450
pool_min_conns = 10
pool_max_conn_lifetime = "1h"
pool_max_conn_idle_time = "30m"
health_check_period = "1m"
connect_timeout = "60s"

[redis]
host = "localhost"
port = "6379"
db = 0
protocol = 3
dial_timeout = "5s"
read_timeout = "3s"
write_timeout = "5s"

[rabbitmq]
url = "amqp://localhost:5672"
exchange = "eventkit" # Really ?
queue_durable = true
queue_auto_delete = false
prefetch_count = 10
reconnect_delay = "5s"
max_reconnect_attempts = 5
