[database]
username = "postgres"
password = "1234"

[redis]
username = ""
password = ""

[rabbitmq]
exchange = "eventkit" # Really ?

[mailer]
host = "smtp.host.name"
port = 56
username = ""
password = ""

[payment]
payu_test_key = ""
payu_test_salt = ""
payu_prod_key = ""
payu_prod_salt = ""
payu_test_verify_url = ""
payu_prod_verify_url = ""
